development:
  adapter: postgresql
  database: my_ruby_on_rails_scalia_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_ruby_on_rails_scalia_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_ruby_on_rails_scalia_production
  pool: 5
  timeout: 5000